### ISSUE TITLE
ResourceNotFound when using the HTML export

### ISSUE THREAD

**Issue by PierreBubu** [lequal/i-CodeCNES#103]
Hello,
I got an issue by using the new feature to directly export i-code reports into an HTML file. Here is the stacktrace : 
Command-line arguments:  -os linux -ws gtk -arch x86_64 -consoleLog -html -htmlOutput /tmp /code/scripts/Populator.sh /code/scripts/extractTriggerRequests.sh

!ENTRY org.eclipse.osgi 4 0 2017-11-02 08:52:18.061
!MESSAGE Application error
!STACK 1
java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(File.java:418)
        at fr.cnes.icode.application.ICodeApplication.generateHtml(ICodeApplication.java:284)
        at fr.cnes.icode.application.ICodeApplication.start(ICodeApplication.java:265)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

I checked into the code, and i guess the problem is well described here : http://blog.vogella.com/2010/07/06/reading-resources-from-plugin/ 
The way URLs are loaded in the code is the one described as first solution in the link ahead. It is known to cause some problems (see https://stackoverflow.com/questions/18055189/why-my-uri-is-not-hierarchical for example). The second way described seems more reliable and maybe should be sue as correction)

Best regards.

**Comment by begarco** [comment]
HTML export will be removed from i-Code in next release, see #133.

**Comment by begarco** [comment]
HTML export is now deprecated.
